// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'EndorsementCard': typeof import('../components/EndorsementCard.vue')['default'],
    'LineReveal': typeof import('../components/LineReveal.vue')['default'],
    'Menu': typeof import('../components/Menu.vue')['default'],
    'OvalButton': typeof import('../components/OvalButton.vue')['default'],
    'ParallaxMedia': typeof import('../components/ParallaxMedia.vue')['default'],
    'SaftLogo': typeof import('../components/SaftLogo.vue')['default'],
    'ScrollAction': typeof import('../components/ScrollAction.vue')['default'],
    'SlideRevealText': typeof import('../components/SlideRevealText.vue')['default'],
    'Splitting': typeof import('../components/Splitting.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
